openapi: "3.0.1"
info:
  title: "Rasa Core - Server Endpoints"
  version: "1.0.0"
  description: >-
    The Rasa Core server provides endpoints to retrieve trackers of
    conversations as well as endpoints to modify them.
paths:
  /:
    get:
      tags:
      - Hello
      summary: Say Hello to Core
      operationId: hello
      responses:
        200:
          description: hello from Rasa Core
  /version:
    get:
      tags:
      - Version
      summary: Fetch versions of Core
      operationId: version
      responses:
        200:
          description: Version of Core
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  minimum_compatible_version:
                    type: string
  /conversations/{sender_id}/execute:
    post:
      tags:
      - Tracker
      summary: >-
        Run an action in a conversation. Note: Any responses sent by
        the executed action will be returned as part of the endpoints
        result, they will not be sent over a connected output channel.
      operationId: executeAction
      parameters:
      - in: path
        name: sender_id
        description: Id of the conversation
        schema:
          type: string
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
              required: ["action"]
      responses:
        200:
          description: Execution of the action suceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  tracker:
                    $ref: '#/components/schemas/Tracker'
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/BotMessage'
        400:
          description: Invalid request format
        500:
          description: An exception occured while running the action

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
    Project:
      type: object
      properties:
        project_id:
          type: string
        role:
          type: string
    Event:
      type: object
      properties:
        event:
          type: string
        timestamp:
          type: float
    BotMessage:
      type: object
      properties:
        recipient_id:
          type: string
        text:
          type: string
        image:
          type: string
        buttons:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              payload:
                type: string
        attachement:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              payload:
                type: string
    Tracker:
      type: object
      properties:
        sender_id:
          type: string
        slots:
          type: array
          items:
            type: object
        latest_message:
          type: object
          properties:
            intent:
              type: string
            text:
              type: string
            entities:
              type: array
              items:
                type: object
                properties:
                  entity:
                    type: string
                  value:
                    type: string
        latest_event_time:
          type: number
        followup_action:
          type: string
        paused:
          type: bool
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        latest_input_channel:
          type: string
