backend:
  - 'pyproject.toml'
  - 'poetry.lock'
  - 'rasa/**/*'
  - 'tests/**/*'
  - 'data/**/*'
  - 'examples/**/*'

docker:
  - 'pyproject.toml'
  - 'poetry.lock'
  - 'rasa/**/*'
  - 'docker/**/*'

docs:
  - 'docs/**/*'
  - 'changelog/*'
  - 'CHANGELOG.mdx'
  - 'tests/docs/*'
  - 'data/**/*'
  - 'examples/**/*'
