repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.0.0
    hooks:
    -   id: doctoc
        files: "CONTRIBUTING.md"
