language: en

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
  - name: "EntitySynonymMapper"

policies:
  - name: MemoizationPolicy
  - name: EmbeddingPolicy
    max_history: 5
    epochs: 100
