language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
    token_pattern: (?u)\b\w+\b
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
    dimensions:
      - number
  - name: DIETClassifier
  - name: EntitySynonymMapper

policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
