name: Assign default project to issues

on:
  issues:
    types:
    - opened

jobs:
  assign_default_project:
    name: Assign default project to issue
    runs-on: ubuntu-latest

    steps:
    - name: Assign vulnerability scans or Sentry issues to Enable
      if: contains(github.event.issue.labels.*.name, 'tool:trivy') || contains(github.event.issue.labels.*.name, 'tool:sentry')
      uses: m-vdb/create-or-update-project-card@9c632af4932aabf8115780d762841f3ca07f7b6b

      with:
        token: ${{ secrets.RASABOT_ASSIGN_ISSUES_BOARD_TOKEN }}
        # https://github.com/orgs/RasaHQ/projects/40
        project-location: RasaHQ
        project-number: 40
        column-name: Inbox
