name: Docs Tests
on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  test_documentation:
    name: Test Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v2

    - name: Set up Python 3.7 🐍
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Set up Node 12.x 🦙
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Read Poetry Version 🔢
      run: |
        echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
      shell: bash

    - name: Install poetry 🦄
      uses: Gr1N/setup-poetry@v4
      with:
        poetry-version: ${{ env.POETRY_VERSION }}

    - name: Load Poetry Cached Libraries ⬇
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-3.7-${{ hashFiles('**/poetry.lock') }}-${{ secrets.POETRY_CACHE_VERSION }}
        restore-keys: ${{ runner.os }}-poetry-3.7

    - name: Load Yarn Cached Packages ⬇
      uses: actions/cache@v2
      with:
        path: docs/node_modules
        key: ${{ runner.os }}-yarn-12.x-${{ hashFiles('docs/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-12.x

    - name: Install Dependencies 📦
      run: |
        sudo apt-get -y install libpq-dev
        make install-full install-docs

    - name: Run Swagger 🕵️‍♀️
      run: |
        npm install -g swagger-cli
        swagger-cli validate docs/static/spec/action-server.yml
        swagger-cli validate docs/static/spec/rasa.yml

    - name: Test Docs 🕸
      run: make test-docs
